CREATE DATABASE USER1
USE USER1
CREATE TABLE ACCOUNT
(
	ID NVARCHAR (10),
	PASS NVARCHAR(10),
)
drop table ACCOUNT
INSERT INTO ACCOUNT VALUES ('01','1234');
INSERT INTO ACCOUNT VALUES ('02','12345');